// Generated by scripts/sync-art.mjs — do not edit. Artwork built from docs/design/assets/*.png into public/art/.
export interface ArtMeta {
  /** Source size in px (after trimming, for the logo). */
  width: number;
  height: number;
  /** Widths of the public/art/<name>-<w>.webp variants. */
  widths: readonly number[];
}

export const ART_META: Readonly<Record<string, ArtMeta>> = {
  "app-icon": {
    "width": 1254,
    "height": 1254,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "banner-bgmi": {
    "width": 2172,
    "height": 724,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280,
      1920
    ]
  },
  "banner-freefire": {
    "width": 2172,
    "height": 724,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280,
      1920
    ]
  },
  "banner-valorant": {
    "width": 2171,
    "height": 724,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280,
      1920
    ]
  },
  "bg-bgmi": {
    "width": 1672,
    "height": 941,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "bg-freefire": {
    "width": 1672,
    "height": 941,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "bg-valorant": {
    "width": 1672,
    "height": 941,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "card-match-bgmi": {
    "width": 1586,
    "height": 992,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "card-match-freefire": {
    "width": 1586,
    "height": 992,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "card-match-valorant": {
    "width": 1586,
    "height": 992,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "card-tournament-bgmi": {
    "width": 1448,
    "height": 1086,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "card-tournament-freefire": {
    "width": 1448,
    "height": 1086,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "card-tournament-valorant": {
    "width": 1448,
    "height": 1086,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "empty-no-matches": {
    "width": 1254,
    "height": 1254,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "empty-no-notifications": {
    "width": 1254,
    "height": 1254,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "empty-no-team": {
    "width": 1254,
    "height": 1254,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "empty-offline": {
    "width": 1254,
    "height": 1254,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "empty-profile": {
    "width": 1254,
    "height": 1254,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "hero-bgmi": {
    "width": 971,
    "height": 1619,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "hero-freefire": {
    "width": 971,
    "height": 1619,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "hero-valorant": {
    "width": 971,
    "height": 1619,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960
    ]
  },
  "logo": {
    "width": 721,
    "height": 737,
    "widths": [
      256,
      384,
      512,
      640
    ]
  },
  "og-background": {
    "width": 1731,
    "height": 909,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "texture-dark": {
    "width": 1672,
    "height": 941,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  },
  "trophy-podium": {
    "width": 1536,
    "height": 1024,
    "widths": [
      256,
      384,
      512,
      640,
      768,
      960,
      1280
    ]
  }
};

export const AVAILABLE_ART: readonly string[] = Object.keys(ART_META);
