// Builds design artwork from docs/design/assets/*.png into public/art/ and writes lib/art-manifest.ts.
// <Artwork name> shows a placeholder for anything not listed, so dropping a new PNG into
// docs/design/assets/ needs no code change (just a rebuild).
//
// For every asset:
//   public/art/<name>-<w>.webp  responsive WebP at the standard widths up to the source width
//   public/art/<name>.png       optimized PNG fallback (≤ 1280 px wide; also used by OG images and icons)
// Unchanged sources are not re-encoded (public/art/.cache.json). Runs on install, dev, build, typecheck, test.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const src = path.join(root, "docs/design/assets");
const out = path.join(root, "public/art");
const manifest = path.join(root, "lib/art-manifest.ts");
const cacheFile = path.join(out, ".cache.json");

/** Bump when the encoding settings change, to rebuild everything once. */
const PIPELINE = "v2";
// Finer steps where phones land (a 72vw hero panel at 1.75–2.6× needs ~520–770 px).
export const WIDTHS = [256, 384, 512, 640, 768, 960, 1280, 1920];
const FALLBACK_MAX = 1280;
/** Per-asset preparation before resizing. logo.png is a gold mark on a black square: trim to the mark. */
const PREPARE = {
  logo: (img) => img.trim({ background: "#000000", threshold: 40 }),
};

const names = existsSync(src)
  ? readdirSync(src)
      .filter((f) => /^[a-z0-9-]+\.png$/.test(f))
      .map((f) => f.slice(0, -4))
      .sort()
  : [];

const fingerprint = (n) => {
  const s = statSync(path.join(src, `${n}.png`));
  return createHash("sha1").update(`${PIPELINE}|${s.size}|${s.mtimeMs}`).digest("hex");
};

async function build(sharp, name) {
  const base = () => {
    const img = sharp(path.join(src, `${name}.png`), { limitInputPixels: false });
    return PREPARE[name] ? PREPARE[name](img) : img;
  };
  // Dimensions after preparation (the logo is trimmed).
  const { info } = await base().toBuffer({ resolveWithObject: true });
  const widths = WIDTHS.filter((w) => w <= info.width);
  if (!widths.length) widths.push(info.width);
  const files = [];
  for (const w of widths) {
    const file = `${name}-${w}.webp`;
    // Transparent art (characters, icons) compresses best at a slightly lower quality; photos keep q76.
    const webp = info.channels === 4 ? { quality: 70, alphaQuality: 80, effort: 6 } : { quality: 76, effort: 5 };
    await base().resize({ width: w, withoutEnlargement: true }).webp(webp).toFile(path.join(out, file));
    files.push(file);
  }
  await base()
    .resize({ width: Math.min(info.width, FALLBACK_MAX), withoutEnlargement: true })
    .png({ compressionLevel: 9, adaptiveFiltering: true, palette: info.channels === 4 })
    .toFile(path.join(out, `${name}.png`));
  files.push(`${name}.png`);
  return { width: info.width, height: info.height, widths, files };
}

async function main() {
  mkdirSync(out, { recursive: true });
  const cache = existsSync(cacheFile) ? JSON.parse(readFileSync(cacheFile, "utf8")) : {};
  const next = {};
  let sharp = null;
  let built = 0;
  for (const name of names) {
    const fp = fingerprint(name);
    const hit = cache[name];
    if (hit && hit.fp === fp && hit.meta.files.every((f) => existsSync(path.join(out, f)))) {
      next[name] = hit;
      continue;
    }
    sharp ??= (await import("sharp")).default;
    next[name] = { fp, meta: await build(sharp, name) };
    built++;
  }
  // Remove outputs of assets that were deleted or re-encoded to other widths.
  const keep = new Set([".cache.json", ...Object.values(next).flatMap((e) => e.meta.files)]);
  for (const f of readdirSync(out)) if (!keep.has(f)) rmSync(path.join(out, f), { force: true });
  writeFileSync(cacheFile, JSON.stringify(next));

  const meta = Object.fromEntries(Object.entries(next).map(([n, e]) => [n, { width: e.meta.width, height: e.meta.height, widths: e.meta.widths }]));
  const body = `// Generated by scripts/sync-art.mjs — do not edit. Artwork built from docs/design/assets/*.png into public/art/.
export interface ArtMeta {
  /** Source size in px (after trimming, for the logo). */
  width: number;
  height: number;
  /** Widths of the public/art/<name>-<w>.webp variants. */
  widths: readonly number[];
}

export const ART_META: Readonly<Record<string, ArtMeta>> = ${JSON.stringify(meta, null, 2)};

export const AVAILABLE_ART: readonly string[] = Object.keys(ART_META);
`;
  const previous = existsSync(manifest) ? readFileSync(manifest, "utf8") : "";
  if (previous !== body) writeFileSync(manifest, body);
  console.log(`sync-art: ${names.length} artwork file(s), ${built} (re)built${built ? "" : " (cached)"}`);
}

await main();
